

// ***************************************************************//
//	     La siguiente petición crea un usuario:                   //
// ***************************************************************//

POST https://localhost:8443/back/create_user HTTP/1.1
Content-Type: application/json

{
	"username": "Ismaelito",
	"password": "1234",
	"email": "ismaelito@gmail.com"
}

// ***************************************************************//
//	     La siguiente petición crea otro usuario con email        //
// ***************************************************************//

POST https://localhost:8443/back/create_user HTTP/1.1
Content-Type: application/json

{
	"username": "trutru2",
	"password": "pass30",
	"email": "trutru2@email.com"
}

// ***************************************************************//
//	     La siguiente petición lanza el login                     //
// ***************************************************************//

POST https://localhost:8443/back/auth/login HTTP/1.1
Content-Type: application/json

{
	"username": "Pepe5@gmail.com",
	"password": "1234",
	"email": "Pepe5@gmail.com"
}


POST https://localhost:8443/back/register_user HTTP/1.1
Content-Type: application/json

{
	"username": "User@gmail.com",
	"password": "1234",
	"email": "Pepe50@gmail.com"
}


// ***************************************************************//
//	     La siguiente petición Obtiene todos los usuarios:        //
// ***************************************************************//

GET https://localhost:8443/back/get_users  HTTP/1.1


// ***************************************************************//
//	    La siguiente petición Obtiene el usuario por username:    //
// ***************************************************************//

GET https://localhost:8443/back/get_user_by_username/?username=pepe@gmail.com  HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlcGU0MEBnbWFpbC5jb20iLCJpYXQiOjE3NDM5MzU2NDksImV4cCI6MTc0MzkzOTI0OX0.2E92SxCN2sF2XPYUEFjtetkQFbHozaYb20gFHJANOoY


// ***************************************************************//		
//	     La siguiente petición elimina usuario por username:      //
// ***************************************************************//

DELETE  https://localhost:8443/back/delete_user  HTTP/1.1
Content-Type: application/json

{
	"username" : "Postname1"
}

// ***************************************************************//
//	     La siguiente petición elimina usuario por userId:        //
// ***************************************************************//

DELETE  https://localhost:8443/back/delete_user_by_id  HTTP/1.1
Content-Type: application/json

{
	"userId" : "2"
}

GET https://localhost:8443/back/get_user_by_id/?id=1  HTTP/1.1

DELETE https://localhost:8443/back/delete_all_users  HTTP/1.1

// para ejecutar las pruebas de la api simplemente seleccionar y pulsar ctrl + alt + R 
// o seleccionar la petición y pulsar boton derecho y send request.

POST https://localhost:8443/back/update_user_by_id HTTP/1.1
Content-Type: application/json

{
	"userId": "11",
	"username": "ElFary",
	"password": "Toritolindoaytoritoguapo",
	"googleId": "Dejalosquecamelen",
	"email": "ElFary@gmail.com",
	"avatarPath": "foto.jpg"
}

POST https://localhost:8443/back/api/data HTTP/1.1
Content-Type: application/json

{
	"userId": "11",
	"username": "ElFary",
	"password": "Toritolindoaytoritoguapo",
	"googleId": "Dejalosquecamelen",
	"email": "ElFary@gmail.com",
	"avatarPath": "foto.jpg"
}

POST https://localhost:8443/back/auth/logout HTTP/1.1
Content-Type: application/json

{
	"username": "User@gmail.com",
	"password": "1234",
	"email": "Pepe50@gmail.com"
}

GET https://localhost:8443/back/auth/verify-token HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZm9uc28gRmVybsOhbmRlel8xMTM4NjQyNzgwNTAzNDA5MTE0NzgiLCJpYXQiOjE3NDM2OTY5NjYsImV4cCI6MTc0MzcwMDU2Nn0.h2L1dBHqGqlbG_eTW6edwS6pvw-pwxVAENGkGZchIvY






eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlcGU0MEBnbWFpbC5jb20iLCJpYXQiOjE3NDM5MzU2NDksImV4cCI6MTc0MzkzOTI0OX0.F9B84eGNdqQ7nsa9nAME_hPp6oNAxiMWjIBLadDr1Qc


// ╔═══════════════════════════════════════════════════════════════════════╗
// ║                              FRIENDS                                  ║
// ║                         RELATIONSHIP HANDLERS                         ║
// ╚═══════════════════════════════════════════════════════════════════════╝

# Petición para enviar una friend_request:
POST https://localhost:8443/back/send_friend_request HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
  "friendId": "1"
}


# Petición para aceptar una friend_request:
POST https://localhost:8443/back/accept_friend_request HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
  "friendId": "1"
}

# Petición para rechazar una friend_request:
POST https://localhost:8443/back/reject_friend_request HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
  "friendId": "1"
}


# Petición para bloquear un usuario:
POST https://localhost:8443/back/block_user HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
  "friendId": "4"
}

# Petición para desbloquear un usuario:
POST https://localhost:8443/back/unblock_user HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
  "friendId": "1"
}

#Petición para eliminar un usuario:
POST https://localhost:8443/back/delete_friend HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
  "friendId": "1"
}

# Petición para tener la lista de relaciones de un usuario:
POST https://localhost:8443/back/get_all_friends_entries_from_an_id HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
}

# Petición para tener la lista de solicitudes pendientes de un usuario:
POST https://localhost:8443/back/get_all_pending_users_from_an_id HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
}


# Petición para tener la lista de amigos de un usuario:
POST https://localhost:8443/back/get_all_accepted_users_from_an_id HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
}

# Petición para tener la lista de bloqueados de un usuario:
POST https://localhost:8443/back/get_all_blocked_users_from_an_id HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
}

# Petición para tener la lista de coincidencias de usuarios por keyword:
POST https://localhost:8443/back/get_all_users_coincidences HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTc0NTU5MTM2MiwiZXhwIjoxNzQ1NTk0OTYyfQ.CO6DJ_eBcUv1Z3DPg01E3Kg99_iqZ3Av3xuktAGEJX0

{
	"keyword": "is"
}
