
// ***************************************************************//
//	       Para usar con extensiones como "REST client"           //
//     	                                                       	  //
//     -- Seleccionar la instrucción y pulsar ctrl+ Alt + r  --   //
//     	                                                       	  //
//  Nota: algunas peticiones requieren autenticación con token    //
//        si no funcionan añadir el token segun sea la petición   //	
//        el token se debe coger inspeccionando el almaceamiento  //
//        de la aplicación. ver: get_user_by_id                   //
// ***************************************************************//


// ***************************************************************//
//	     La siguiente petición crea un usuario:                   //
// ***************************************************************//

POST https://localhost:8443/back/create_user HTTP/1.1
Content-Type: application/json

{
	"username": "Ismael_Moro4",
	"password": "1234",
	"email": "ismael4@gmail.com"
}

// ***************************************************************//
//	     La siguiente petición crea otro usuario con email        //
// ***************************************************************//

POST https://localhost:8443/back/create_user HTTP/1.1
Content-Type: application/json

{
	"username": "trutru2",
	"password": "pass30",
	"email": "trutru2@email.com"
}

// ***************************************************************//
//	     La siguiente petición lanza el login                     //
// ***************************************************************//

POST https://localhost:8443/back/auth/login HTTP/1.1
Content-Type: application/json

{
	"password": "A12345678!<script>alert('hola')</script>",
	"email": "alfonso2@gmail.com<script>alert('hola')</script>"
}

POST https://localhost:8443/back/auth/login HTTP/1.1
Content-Type: application/json

{
	"password": "A12345678!",
	"email": "alfonso2@gmail.com"
}


POST https://localhost:8443/back/auth/login HTTP/1.1
Content-Type: application/json

{
	"username": "alfonso2",
	"password": "A12345678!",
	"email": "alfonso2@gmail.com"
}


POST https://localhost:8443/back/register_user HTTP/1.1
Content-Type: application/json

{
	"username": "Usergmailcom2pass<script>alert('hola')</script>word",
	"password": "1234<script>alert('hola')</script>word",
	"email": "Pepe50@gmail.com<script>alert('hola')</script>word"
}



POST https://localhost:8443/back/register_user HTTP/1.1
Content-Type: application/json

{
	"username": "Usergmailcom2",
	"password": "1234word",
	"email": "Pepe50@gmail.com"
}




// ***************************************************************//
//	     La siguiente petición Obtiene todos los usuarios:        //
// ***************************************************************//

GET https://localhost:8443/back/get_users  HTTP/1.1


// ***************************************************************//
//	    La siguiente petición Obtiene el usuario por username:    //
// ***************************************************************//

GET https://localhost:8443/back/get_user_by_username/?username=ismael  HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0ODcwNTAzOSwiZXhwIjoxNzQ4NzA4NjM5fQ.VfxdQMtnojvXh4iqQTslWIuQroK9uYINjbG8a_zQvPs


// ***************************************************************//		
//	     La siguiente petición elimina usuario por username:      //
// ***************************************************************//

DELETE  https://localhost:8443/back/delete_user  HTTP/1.1
Content-Type: application/json

{
	"username" : "Postname1"
}





// ***************************************************************//
//	     La siguiente petición elimina usuario por userId:        //
// ***************************************************************//

DELETE  https://localhost:8443/back/delete_user_by_id  HTTP/1.1
Content-Type: application/json

{
	"userId" : "2"
}

// ejemplo de token para las siguientes peticiones
GET https://localhost:8443/back/get_user_by_id/?id=1  HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2NTcwMDA4NiwiZXhwIjoxNzY1NzE0NDg2fQ.SKD88s03eAeh7G0GD2w4LxT6jdZm7ZMUvmcFqMvHGgA


DELETE https://localhost:8443/back/delete_all_users  HTTP/1.1

// para ejecutar las pruebas de la api simplemente seleccionar y pulsar ctrl + alt + R 
// o seleccionar la petición y pulsar boton derecho y send request.

POST https://localhost:8443/back/update_user_by_id HTTP/1.1
Content-Type: application/json

{
	"userId": "11",
	"username": "ElFary",
	"password": "Toritolindoaytoritoguapo",
	"googleId": "Dejalosquecamelen",
	"email": "ElFary@gmail.com",
	"avatarPath": "foto.jpg"
}


POST https://localhost:8443/back/verify_guest_tournamentName HTTP/1.1
Content-Type: application/json

{
	"guestTName": "Ai002trutru"
}


POST https://localhost:8443/back/api/data HTTP/1.1
Content-Type: application/json

{
	"userId": "11",
	"username": "ElFary",
	"password": "Toritolindoaytoritoguapo",
	"googleId": "Dejalosquecamelen",
	"email": "ElFary@gmail.com",
	"avatarPath": "foto.jpg"
}

POST https://localhost:8443/back/auth/logout HTTP/1.1
Content-Type: application/json

{
	"username": "User@gmail.com",
	"password": "1234",
	"email": "Pepe50@gmail.com"
}


GET https://localhost:8443/back/auth/verify-token HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc2NTcwMDA4NiwiZXhwIjoxNzY1NzE0NDg2fQ.SKD88s03eAeh7G0GD2w4LxT6jdZm7ZMUvmcFqMvHGgA



GET https://localhost:8443/back/get_gamelogs HTTP/1.1

GET https://localhost:8443/back/get_chessgamelogs HTTP/1.1

GET https://localhost:8443/back/get_user_chessgamelogs/2 HTTP/1.1
GET https://localhost:8443/back/get_user_gamelogs/1 HTTP/1.1

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkxOTExNCwiZXhwIjoxNzQ1OTIyNzE0fQ.-H8R_Up98hoHh6XEkjAZHD5v1ilf3CJc1M006dGCwtE

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTc0NTkxOTE0NSwiZXhwIjoxNzQ1OTIyNzQ1fQ.00XlKPvaU7YBJZOZPeZdouZI9h2Cbl0IvNCrI7Rcnso

# /** para crear datos " a mano" en gamelogs dar permisos 777 a la base de datos
# abrirla con DB Browser for SQlite y ejectuar insert*/
	INSERT INTO gamelogs (user1, user2, winner, loser, duration, game_id, tournament_id, created_at, updated_at)
	VALUES
	(1, 2, 1, 2, 3500, 'game_001', 'tournament_001', DATETIME('now'), DATETIME('now')),
	(3, 4, 3, 4, 4200, 'game_002', NULL, DATETIME('now'), DATETIME('now')),
	(5, 6, 6, 5, 2800, 'game_003', 'tournament_002', DATETIME('now'), DATETIME('now')),
	(7, 8, 7, 8, 3100, 'game_004', NULL, DATETIME('now'), DATETIME('now')),
	(2, 3, 3, 2, 3900, 'game_005', 'tournament_001', DATETIME('now'), DATETIME('now'));

# Actualiar los datos de gamelogs
	UPDATE gamelogs
	SET winner = 2,
	    loser = 1,
	    game_id = 'game_000',
	    updated_at = DATETIME('now')
	WHERE id = 2;
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlBlcGU0MEBnbWFpbC5jb20iLCJpYXQiOjE3NDM5MzU2NDksImV4cCI6MTc0MzkzOTI0OX0.F9B84eGNdqQ7nsa9nAME_hPp6oNAxiMWjIBLadDr1Qc


// ╔═══════════════════════════════════════════════════════════════════════╗
// ║                              FRIENDS                                  ║
// ║                         RELATIONSHIP HANDLERS                         ║
// ╚═══════════════════════════════════════════════════════════════════════╝

# Petición para enviar una friend_request:
POST https://localhost:8443/back/send_friend_request HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
  "friendId": "1"
}


# Petición para aceptar una friend_request:
POST https://localhost:8443/back/accept_friend_request HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
  "friendId": "1"
}

# Petición para rechazar una friend_request:
POST https://localhost:8443/back/reject_friend_request HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
  "friendId": "1"
}


# Petición para bloquear un usuario:
POST https://localhost:8443/back/block_user HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0OTU1MTc0NCwiZXhwIjoxNzQ5NTU1MzQ0fQ.GuMabskXTupDirWcDrmsPm_HsMnQKY-lSKlHDn7p3MQ

{
  "friendId": "2"
}

# Petición para desbloquear un usuario:
POST https://localhost:8443/back/unblock_user HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0OTQ2MzE5NywiZXhwIjoxNzQ5NDY2Nzk3fQ._luNYWonlGDC26FrrLZCnBfvP-FsGaeP2J4ZMx_6MrI

{
  "friendId": "2"
}

#Petición para eliminar un usuario:
POST https://localhost:8443/back/delete_friend HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
  "friendId": "1"
}

# Petición para tener la lista de relaciones de un usuario:
POST https://localhost:8443/back/get_all_friends_entries_from_an_id HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0Njg2ODgwOSwiZXhwIjoxNzQ2ODcyNDA5fQ.ufRauLJfr9QF2HpYk74QHOKyeu-mixnirmkx7IvI320

{
}

# Petición para tener la lista de solicitudes pendientes de un usuario:
POST https://localhost:8443/back/get_all_pending_users_from_an_id HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
}


# Petición para tener la lista de amigos de un usuario:
POST https://localhost:8443/back/get_all_accepted_users_from_an_id HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
}

# Petición para tener la lista de bloqueados de un usuario:
POST https://localhost:8443/back/get_all_blocked_users_from_an_id HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
}

# Petición para tener la lista de coincidencias de usuarios por keyword:
POST https://localhost:8443/back/get_all_users_coincidences HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
	"keyword": "is"
}

// ***************************************************************//
//	     Las siguientes peticiones verifican el usuario:               //
//       player 2 o más usa email y password para verificar       //
//       player 1 no envía nada en el body y usa token		      //
//       														  //
// ***************************************************************//

POST https://localhost:8443/back/verify_user HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0NTkyMDY3NCwiZXhwIjoxNzQ1OTI0Mjc0fQ.1caxFQLJ4IEGrvmgXJfTK18X2CVaMRJLfpzMdl_PaTs

{
	"email": "alfonso@gmail.com",
	"password": "1234"
}


POST https://localhost:8443/back/verify_user HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0Njg2ODgwOSwiZXhwIjoxNzQ2ODcyNDA5fQ.ufRauLJfr9QF2HpYk74QHOKyeu-mixnirmkx7IvI320

{
	"email": "",
	"password": ""
}

POST https://localhost:8443/back/verify_user HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc0Njg2ODgwOSwiZXhwIjoxNzQ2ODcyNDA5fQ.ufRauLJfr9QF2HpYk74QHOKyeu-mixnirmkx7IvI320
DELETE https://localhost:8443/back/delete_tournamentlogs HTTP/1.1
{
}

// ***************************************************************//

POST https://localhost:8443/back/getIdByUsername HTTP/1.1
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc0ODcwNTAzOSwiZXhwIjoxNzQ4NzA4NjM5fQ.VfxdQMtnojvXh4iqQTslWIuQroK9uYINjbG8a_zQvPs

{
	"username": "efweg"
}


POST https://localhost:8443/back/create_temp_user HTTP/1.1
Content-Type: application/json

{
	"tournamentId": "42",
	"tournamentName": "Ai002trutru2"
}


POST https://localhost:8443/back/create_temp_user HTTP/1.1
Content-Type: application/json

{
	"tournamentId": "423",
	"tournamentName": "Ai002trutru13"
}

GET https://localhost:8443/back/get_temp_users HTTP/1.1

DELETE https://localhost:8443/back/delete_user_by_tournament_id HTTP/1.1
Content-Type: application/json

{
	"TournamentId": "26"
}

POST https://localhost:8443/back/clean_temp_user_after_closing HTTP/1.1
Content-Type: application/json

{
	"tournamentId": "26"
}

DELETE https://localhost:8443/back/delete_all_temp_users HTTP/1.1

// ***************************************************************//

DELETE https://localhost:8443/back/delete_tournamentlogs HTTP/1.1

GET https://localhost:8443/back/get_next_tournamentlog HTTP/1.1


GET https://localhost:8443/back/get_tournamentlogs HTTP/1.1

# Crear un tournamentlog
POST https://localhost:8443/back/create_tournamentlog HTTP/1.1
Content-Type: application/json

{
	"tournamentId": "123",
	"playerscount": 8,
	"config": { 
			"numberOfPlayers": "6",
			"scoreLimit": "5",
			"difficulty": "medium"
			},
	"users": [
		{
			"Index": "1",
			"status": "ready",
			"gameplayer": {
				// propiedades de GamePlayer aquí
			}
		},
		{
			"Index": "2",
			"status": "ready",
			"gameplayer": {
				// propiedades de GamePlayer aquí
			}
		},
		{
			"Index": "3",
			"status": "ready",
			"gameplayer": {
				// propiedades de GamePlayer aquí
			}
		},
		{
			"Index": "4",
			"status": "ready",
			"gameplayer": {
				// propiedades de GamePlayer aquí
			}
		},
		{
			"Index": "5",
			"status": "ready",
			"gameplayer": {
				// propiedades de GamePlayer aquí
			}
		},
		{
			"Index": "6",
			"status": "ready",
			"gameplayer": {
				// propiedades de GamePlayer aquí
			}
		},
		{
			"Index": "7",
			"status": "ready",
			"gameplayer": {
				// propiedades de GamePlayer aquí
			}
		},
		{
			"Index": "8",
			"status": "ready",
			"gameplayer": {
				// propiedades de GamePlayer aquí
			}
		}
	],
	"gamesData": [
		{ "gameId": "game1", "winner": 1 },
		{ "gameId": "game2", "winner": 2 }
	]
}

# Actualizar un tournamentlog todo: corregir la información de users y gamesData con valores reales
POST https://localhost:8443/back/update_tournamentlog HTTP/1.1
Content-Type: application/json

{
	"tournamentId": "123",
	"playerscount": 8,
	"config": { 
		"numberOfPlayers": "6",
		"scoreLimit": "5",
		"difficulty": "medium"
		},
	"users": [1, 2, 3, 4, 5, 6, 7, 8],
	"gamesData": [
		{ "gameId": "game1", "winner": 1 },
		{ "gameId": "game2", "winner": 2 }
	],
	"winner": 1
}


# Crear un tournamentlog todo: corregir la información de users y gamesData con valores reales
POST https://localhost:8443/back/create_tournamentlog HTTP/1.1
Content-Type: application/json

{
	"tournamentId": "124"
}

# Actualizar un tournamentlog
POST https://localhost:8443/back/update_tournamentlog HTTP/1.1
Content-Type: application/json

{
	"tournamentId": "123",
	"playerscount": 8,
	"config": { 
		"numberOfPlayers": "6",
		"scoreLimit": "5",
		"difficulty": "medium"
		},
	"winner": 5
}

POST https://localhost:8443/back/updateBracket HTTP/1.1
Content-Type: application/json

[
{
"id": "11-match-1",
"mode": "auto",
"player1": {
  "id": "4 + 5",
  "username": "Ai004",
  "tournamentUsername": "Ai004",
  "email": "ai4@transcendence.com",
  "avatarPath": "https://localhost:8443/back/images/avatar-14.png"
},
"player2": {
  "id": "2 + 5",
  "username": "Ai002",
  "tournamentUsername": "Ai002",
  "email": "ai2@transcendence.com",
  "avatarPath": "https://localhost:8443/back/images/avatar-12.png"
},
"startTime": 1752511545001,
"config": {
  "scoreLimit": 5,
  "difficulty": "medium"
},
"result": {
  "winner": "4 + 5",
  "loser": "2 + 5",
  "score": [
	5,
	0
  ]
},
"duration": 0,
"tournamentId": 11,
"readyState": true
},
{
"id": "11-match-2",
"mode": "1vAI",
"player1": {
  "id": "3 + 5",
  "username": "Ai003",
  "tournamentUsername": "Ai003",
  "email": "ai3@transcendence.com",
  "avatarPath": "https://localhost:8443/back/images/avatar-13.png"
},
"player2": {
  "id": 2,
  "username": "alfonso",
  "tournamentUsername": "alfonso",
  "email": "alfonso@gmail.com",
  "avatarPath": "https://localhost:8443/back/images/avatar-18.png"
},
"startTime": 1752511545005,
"config": {
  "scoreLimit": 5,
  "difficulty": "medium"
},
"result": {
  "winner": "",
  "loser": "",
  "score": [
	0,
	0
  ]
},
"duration": 0,
"tournamentId": 11,
"readyState": false
}
]
